#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import * as z from 'zod/v4';
import { readFile } from 'node:fs/promises';
import { fsOps, shell, spawnProcess, systemInfo, launchApp, closeApp, screenshot, mouseMove, mouseClick, typeText, hotkey, clipboardGet, clipboardSet } from './platform.js';

const server = new McpServer({ name: 'omni-commander', version: '0.1.0' });
const text = (value: unknown) => ({ content: [{ type: 'text' as const, text: typeof value === 'string' ? value : JSON.stringify(value, null, 2) }] });
const guarded = async <T>(fn: () => Promise<T>) => { try { return text(await fn()); } catch (e) { return { isError: true, ...text(e instanceof Error ? e.message : String(e)) }; } };

server.registerTool('system_info', { description: 'Return operating-system, architecture, host, home and Node runtime details.', inputSchema: z.object({}) }, async () => text(systemInfo()));
server.registerTool('run_command', { description: 'Run an arbitrary command through PowerShell on Windows or /bin/sh on macOS/Linux.', inputSchema: z.object({ command: z.string(), cwd: z.string().optional(), timeoutMs: z.number().int().positive().max(900000).default(120000) }) }, async a => guarded(() => shell(a.command, a.cwd, a.timeoutMs)));
server.registerTool('spawn_process', { description: 'Start a detached process or application and return its PID.', inputSchema: z.object({ command: z.string(), args: z.array(z.string()).default([]), cwd: z.string().optional() }) }, async a => text(spawnProcess(a.command, a.args, a.cwd)));
server.registerTool('read_file', { description: 'Read a UTF-8 text file from any path permitted to the local agent process.', inputSchema: z.object({ path: z.string() }) }, async a => guarded(() => fsOps.readText(a.path)));
server.registerTool('write_file', { description: 'Create or replace a UTF-8 text file.', inputSchema: z.object({ path: z.string(), content: z.string() }) }, async a => guarded(() => fsOps.writeText(a.path, a.content)));
server.registerTool('list_directory', { description: 'List files and directories with metadata.', inputSchema: z.object({ path: z.string() }) }, async a => guarded(() => fsOps.list(a.path)));
server.registerTool('create_directory', { description: 'Create a directory recursively.', inputSchema: z.object({ path: z.string() }) }, async a => guarded(async () => { await fsOps.mkdir(a.path); return true; }));
server.registerTool('delete_path', { description: 'Delete a file or directory.', inputSchema: z.object({ path: z.string(), recursive: z.boolean().default(false) }) }, async a => guarded(async () => { await fsOps.remove(a.path, a.recursive); return true; }));
server.registerTool('move_path', { description: 'Move or rename a file/directory.', inputSchema: z.object({ from: z.string(), to: z.string() }) }, async a => guarded(async () => { await fsOps.move(a.from, a.to); return true; }));
server.registerTool('copy_file', { description: 'Copy a file.', inputSchema: z.object({ from: z.string(), to: z.string() }) }, async a => guarded(async () => { await fsOps.copy(a.from, a.to); return true; }));
server.registerTool('launch_application', { description: 'Launch an application cross-platform.', inputSchema: z.object({ target: z.string(), args: z.array(z.string()).default([]) }) }, async a => guarded(() => launchApp(a.target, a.args)));
server.registerTool('close_application', { description: 'Close/terminate an application by process or application name.', inputSchema: z.object({ name: z.string() }) }, async a => guarded(() => closeApp(a.name)));
server.registerTool('capture_screen', { description: 'Capture the primary screen and return it as image content for computer-use reasoning.', inputSchema: z.object({ path: z.string().default('./omni-screen.png') }) }, async a => guarded(async () => { const p = await screenshot(a.path); const data = await readFile(p); return { path: p, base64: data.toString('base64') }; }));
server.registerTool('capture_screen_image', { description: 'Capture the primary screen and return a directly viewable PNG image.', inputSchema: z.object({ path: z.string().default('./omni-screen.png') }) }, async a => { try { const p = await screenshot(a.path); const data = await readFile(p); return { content: [{ type: 'image' as const, data: data.toString('base64'), mimeType: 'image/png' }, { type: 'text' as const, text: p }] }; } catch (e) { return { isError: true, ...text(e instanceof Error ? e.message : String(e)) }; } });
server.registerTool('mouse_move', { description: 'Move the mouse pointer to absolute screen coordinates.', inputSchema: z.object({ x: z.number().int(), y: z.number().int() }) }, async a => guarded(() => mouseMove(a.x, a.y)));
server.registerTool('mouse_click', { description: 'Click left, middle, or right mouse button, optionally at coordinates.', inputSchema: z.object({ button: z.enum(['left','middle','right']).default('left'), x: z.number().int().optional(), y: z.number().int().optional() }) }, async a => guarded(() => mouseClick(a.button, a.x, a.y)));
server.registerTool('keyboard_type', { description: 'Type text into the currently focused application.', inputSchema: z.object({ text: z.string() }) }, async a => guarded(() => typeText(a.text)));
server.registerTool('keyboard_hotkey', { description: 'Send a keyboard shortcut/hotkey to the focused application.', inputSchema: z.object({ keys: z.array(z.string()).min(1) }) }, async a => guarded(() => hotkey(a.keys)));
server.registerTool('clipboard_get', { description: 'Read text from the OS clipboard.', inputSchema: z.object({}) }, async () => guarded(() => clipboardGet()));
server.registerTool('clipboard_set', { description: 'Write text to the OS clipboard.', inputSchema: z.object({ text: z.string() }) }, async a => guarded(() => clipboardSet(a.text)));
server.registerTool('list_processes', { description: 'List running processes using the native OS command.', inputSchema: z.object({ filter: z.string().optional() }) }, async a => guarded(async () => { const cmd = process.platform === 'win32' ? `Get-Process${a.filter ? ` | Where-Object {$_.ProcessName -like '*${a.filter.replaceAll("'", "''")}*'}` : ''} | Select-Object Id,ProcessName,CPU,WorkingSet | ConvertTo-Json` : `ps -axo pid,ppid,user,%cpu,%mem,command${a.filter ? ` | grep -i -- ${JSON.stringify(a.filter)}` : ''}`; return shell(cmd); }));
server.registerTool('kill_process', { description: 'Force terminate a process by PID.', inputSchema: z.object({ pid: z.number().int().positive() }) }, async a => guarded(() => shell(process.platform === 'win32' ? `Stop-Process -Id ${a.pid} -Force` : `kill -9 ${a.pid}`)));
server.registerTool('list_services', { description: 'List operating-system services.', inputSchema: z.object({ filter: z.string().optional() }) }, async a => guarded(() => shell(process.platform === 'win32' ? `Get-Service${a.filter ? ` | Where-Object {$_.Name -like '*${a.filter}*'}` : ''} | ConvertTo-Json` : process.platform === 'darwin' ? 'launchctl list' : `systemctl list-units --type=service --all --no-pager${a.filter ? ` | grep -i -- ${JSON.stringify(a.filter)}` : ''}`)));
server.registerTool('service_control', { description: 'Start, stop, restart, enable or disable an OS service.', inputSchema: z.object({ name: z.string(), action: z.enum(['start','stop','restart','enable','disable']) }) }, async a => guarded(() => shell(process.platform === 'win32' ? `${a.action === 'restart' ? `Restart-Service` : a.action === 'start' ? 'Start-Service' : a.action === 'stop' ? 'Stop-Service' : a.action === 'enable' ? 'Set-Service -StartupType Automatic -Name' : 'Set-Service -StartupType Disabled -Name'} ${JSON.stringify(a.name)}` : process.platform === 'darwin' ? `launchctl ${a.action} ${JSON.stringify(a.name)}` : `systemctl ${a.action} ${JSON.stringify(a.name)}`)));
server.registerTool('network_info', { description: 'Return interfaces, routes, DNS, and listening connections.', inputSchema: z.object({}) }, async () => guarded(() => shell(process.platform === 'win32' ? 'Get-NetIPConfiguration | Format-List; Get-NetTCPConnection -State Listen | Select LocalAddress,LocalPort,OwningProcess' : process.platform === 'darwin' ? 'ifconfig; netstat -rn; lsof -nP -iTCP -sTCP:LISTEN' : 'ip addr; ip route; ss -lntup')));
server.registerTool('package_manager', { description: 'Run the native package manager (winget, brew, apt/dnf/pacman) with supplied arguments.', inputSchema: z.object({ args: z.array(z.string()) }) }, async a => guarded(() => shell(process.platform === 'win32' ? `winget ${a.args.join(' ')}` : process.platform === 'darwin' ? `brew ${a.args.join(' ')}` : `(command -v apt-get >/dev/null && sudo apt-get ${a.args.join(' ')}) || (command -v dnf >/dev/null && sudo dnf ${a.args.join(' ')}) || (command -v pacman >/dev/null && sudo pacman ${a.args.join(' ')})`)));
server.registerTool('windows_registry', { description: 'Windows-only registry query/set/delete through PowerShell.', inputSchema: z.object({ operation: z.enum(['get','set','delete']), path: z.string(), name: z.string().optional(), value: z.string().optional() }) }, async a => guarded(() => { if (process.platform !== 'win32') throw new Error('Windows only'); const cmd = a.operation === 'get' ? `Get-ItemProperty -Path ${JSON.stringify(a.path)}${a.name ? ` -Name ${JSON.stringify(a.name)}` : ''} | ConvertTo-Json` : a.operation === 'set' ? `New-Item -Path ${JSON.stringify(a.path)} -Force | Out-Null; Set-ItemProperty -Path ${JSON.stringify(a.path)} -Name ${JSON.stringify(a.name)} -Value ${JSON.stringify(a.value)}` : `Remove-ItemProperty -Path ${JSON.stringify(a.path)} -Name ${JSON.stringify(a.name)}`; return shell(cmd); }));

const transport = new StdioServerTransport();
await server.connect(transport);
